#!/usr/bin/env ruby

require 'cgi'

class GetLyrics
  def initialize
    @current_file = ""
    read_current_file
  end

  def read_current_file
    File.open("/tmp/current_song", 'r') do |f|
      @current_file = f.gets.strip.gsub(/ - /, ' ')
    end
  end

  def current_file
    CGI.escape(@current_file)
  end
end

#system "open 'http://google.com/search?q=#{GetLyrics.new.current_file})+lyrics&btnI=I%27m+Feeling+Lucky'"
system "open 'http://google.com/search?q=#{GetLyrics.new.current_file})+lyrics'"
