#!/bin/bash

# For this to work, whatever pianobar is using as event_command needs to do
# something like:
# print $sfh "$1. $2\n" if (/station(\d+)=(.+)$/);
# into /tmp/pianobar_stations

LINE=$(fgrep playing /tmp/pianobar_stations | sed -e 's/\([0-9]\+\)\..*/\1/')

STATION=$(cat /tmp/pianobar_stations | \
	dmenu -p "Station: " -lines 20 -levenshtein-sort -l $LINE | \
	sed -e 's/\([0-9]\+\)\..*/\1/')

[[ -n $STATION ]] && echo "s$STATION" > ~/.config/pianobar/ctl
